#!/bin/sh

### Package: pbp-install-jellyfin-kodi
### Version: v20200619.1820
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: linux, ffmpeg, kodi

## VARS
DATE=`date +%Y%m%d%H%S`
RESDIR=`pwd`/resources
DEVDIR=`pwd`/upstream
GITREPO=https://github.com/jellyfin
GITTREE=jellyfin-kodi
GITBRANCH=master
PKGDIR=plugin.video.jellyfin

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS ]; then
 if [ $INSTALLDEPS = debian ]; then
  sudo apt-get -y install git build-essential coreutils patch zip
 fi
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --depth=1 $GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -f
git reset --hard
git pull

## PATCH
patch -p0 < $RESDIR/jellyfin-kodi/matrix/jellyfin-kodi_matrix.diff

## ZIP
cd ..
zip -r plugin.video.jellyfin_git$DATE.zip plugin.video.jellyfin

## EXIT
exit

## ENJOY

## POST SCRIPT INSTALL
# install zip package manually in kodi via ui
