#!/bin/sh

### Package: pbp-build-linux-hwaccel
### Version: v20200613.2355
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## VARS
RESDIR=`pwd`/resources
DEVDIR=`pwd`/upstream
LINUXREL=5.7

## OVERRIDE stable with HWACCELREL=testing
if [ -z $HWACCELREL ]; then
 HWACCELREL=stable
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GET
rm -Rf linux-$LINUXREL
[ -f linux-$LINUXREL.tar.xz ] || wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-$LINUXREL.tar.xz
tar xf linux-$LINUXREL.tar.xz
cd linux-$LINUXREL

## PATCH
patch -p1 < $RESDIR/linux/linux-pinebookpro-hwaccel_current-$HWACCELREL.diff

## CONFIGURE
cp $RESDIR/linux/hwaccel-config_current .config
make oldconfig
make menuconfig

## BUILD
make -j `nproc` INITRD=yes KBUILD_IMAGE=arch/arm64/boot/Image bindeb-pkg

## EXIT
exit

## ENJOY

## POST SCRIPT
# install manually with dpkg
