#!/bin/sh

### Package: pbp-build-ffmpeg-v4l2request
### Version: v20200613.1245
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: linux-hwaccel

## VARS
RESDIR=`pwd`/resources
DEVDIR=`pwd`/upstream
FFMPEGREL=4.2.3

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR
rm -Rf ffmpeg-$FFMPEGREL

## DOWNLOAD
[ -f ffmpeg-$FFMPEGREL.tar.bz2 ] || wget https://ffmpeg.org/releases/ffmpeg-$FFMPEGREL.tar.bz2
tar xf ffmpeg-$FFMPEGREL.tar.bz2

## PATCH
cd ffmpeg-$FFMPEGREL
patch -p1 < $RESDIR/ffmpeg/4.2.2/ffmpeg_v4l2-request-hwaccel-4.2.2-rkvdec_20200610.diff

## CONFIGURE
./configure --enable-v4l2-request --enable-libdrm --enable-libudev --enable-pic \
--enable-shared --prefix=/usr/local --incdir=/usr/local/include/aarch64-linux-gnu \
--libdir=/usr/local/lib/aarch64-linux-gnu --shlibdir=/usr/local/lib/aarch64-linux-gnu

## BUILD
make -j `nproc`

## INSTALL
sudo make install
sudo ldconfig

## EXIT
exit

## ENJOY
