#!/bin/sh

### Package: pbp-install-ffmpeg
### Version: v20200623.2100
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: linux

## VARS
RESDIR=`pwd`/resources
DEVDIR=`pwd`/upstream
GITREPO=https://github.com/ffmpeg
GITTREE=ffmpeg

# Override n4.3 with <branch> i.e. release/4.3, master, etc.
if [ -z $GITBRANCH ]; then
 GITBRANCH=n4.3
fi
echo "\n*** GITBRANCH selected is $GITBRANCH.\n"

## OVERRIDES
# Override basic with standard or full
if [ -z $BUILDCONFIG ]; then
 BUILDCONFIG=basic
fi
echo "\n*** BUILDCONFIG selected is $BUILDCONFIG.\n"

# Override 4.3 with 4.2 to apply 4.2 patch. NOTE: 4.3 patch also applies to master.
if [ -z $FFMPEGREL ]; then
 FFMPEGREL=4.3
fi
echo "\n*** FFMPEGREL selected is $FFMPEGREL.\n"

PKGDIR=$GITTREE\_$GITBRANCH

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS ]; then
 if [ $INSTALLDEPS = debian ]; then
  sudo apt-get -y build-dep ffmpeg
  sudo apt-get -y install build-essential coreutils libc-bin wget tar bzip2 patch make \
  libudev-dev libdrm-dev
 fi
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --depth=1 $GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -f
git reset --hard HEAD
git pull

## PATCH
patch -p1 < $RESDIR/ffmpeg/$FFMPEGREL/current_v4l2request

## CONFIGURE
if [ $BUILDCONFIG = basic ]; then
 echo "\n*** Using basic BUILDCONFIG.\n"
 ./configure --enable-v4l2-request --enable-libdrm --enable-libudev --enable-pic --enable-shared \
 --enable-avfilter --enable-postproc --enable-avresample --enable-pthreads --enable-gpl \
 --enable-nonfree --enable-version3 --toolchain=hardened --prefix=/usr/local \
 --libdir=/usr/local/lib/aarch64-linux-gnu --shlibdir=/usr/local/lib/aarch64-linux-gnu
fi
if [ $BUILDCONFIG = standard ]; then
 echo "\n*** Using standard BUILDCONFIG.\n"
 ./configure --enable-v4l2-request --enable-libdrm --enable-libudev --enable-pic --enable-shared \
 --enable-avfilter --enable-postproc --enable-avresample --enable-pthreads --enable-gpl \
 --enable-nonfree --enable-version3  --toolchain=hardened --prefix=/usr/local \
 --libdir=/usr/local/lib/aarch64-linux-gnu --shlibdir=/usr/local/lib/aarch64-linux-gnu \
 --enable-avfilter --enable-gcrypt --enable-libass --enable-libbluray --enable-libdav1d \
 --enable-libfdk-aac --enable-libfontconfig --enable-libfreetype --enable-libmp3lame \
 --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse \
 --enable-librsvg --enable-libspeex --enable-libsrt --enable-libtheora --enable-libtwolame \
 --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 \
 --enable-libxml2 --enable-libxvid --enable-opengl --enable-openssl --enable-libx264
fi
if [ $BUILDCONFIG = full ]; then
 echo "\n*** Using full BUILDCONFIG.\n"
 ./configure --enable-v4l2-request --enable-libdrm --enable-libudev --enable-pic --enable-shared \
 --enable-avfilter --enable-postproc --enable-avresample --enable-pthreads --enable-gpl \
 --enable-nonfree --enable-version3 --toolchain=hardened --prefix=/usr/local \
 --libdir=/usr/local/lib/aarch64-linux-gnu --shlibdir=/usr/local/lib/aarch64-linux-gnu \
 --enable-avfilter --enable-gcrypt --enable-libass --enable-libbluray --enable-libdav1d \
 --enable-libfdk-aac --enable-libfontconfig --enable-libfreetype --enable-libmp3lame \
 --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse \
 --enable-librsvg --enable-libspeex --enable-libsrt --enable-libtheora --enable-libtwolame \
 --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 \
 --enable-libxml2 --enable-libxvid --enable-opengl --enable-openssl --enable-libx264 \
 --enable-ladspa --enable-libaom --enable-libaribb24 --enable-libbs2b --enable-libcaca \
 --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfribidi \
 --enable-libgme --enable-libgsm --enable-libilbc --enable-libjack --enable-libkvazaar --enable-liblensfun \
 --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librubberband \
 --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtesseract --enable-libvidstab \
 --enable-libvo-amrwbenc --enable-libwebp --enable-libzimg --enable-libzmq --enable-libzvbi \
 --enable-lv2 --enable-openal --enable-opencl --enable-chromaprint --enable-frei0r \
 --enable-libiec61883 --enable-libdc1394
fi

## BUILD
make -j `nproc`

## INSTALL
sudo make install
sudo ldconfig

## EXIT
exit

## ENJOY
