#!/bin/sh

### Package: pbp-reset-emmc
### Version: v20200629.2200
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## RUN
echo "\n*** Resetting emmc.\n"
echo "fe330000.sdhci" | sudo tee /sys/bus/platform/drivers/sdhci-arasan/unbind
sleep 3
echo "fe330000.sdhci" | sudo tee /sys/bus/platform/drivers/sdhci-arasan/bind

## EXIT
exit

## ENJOY
