#!/bin/sh

### Package: pbp-build-sway
### Version: v20200614.1420
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## VARS
RESDIR=`pwd`/resources
DEVDIR=`pwd`/upstream
GITREPO=https://github.com/swaywm
GITBRANCH=master

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## LOOP
for GITTREE in wlroots sway swaybg swayidle swaylock;do
 ## VAR
 PKGDIR=$GITTREE\_$GITBRANCH

 ## GIT
 [ -d $PKGDIR ] || git clone --depth=1 $GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
 cd $PKGDIR
 git clean -f
 git reset --hard
 git pull

 ## CLEAN
 rm -Rf pbp-build

 ## CONFIGURE
 meson pbp-build -Dprefix=/usr/local -Dbuildtype=release --libdir=/usr/local/lib/aarch64-linux-gnu

 ## BUILD
 ninja -C pbp-build

 ## INSTALL
 sudo ninja -C pbp-build install
 sudo ldconfig

 ## BACK
 cd ..
done

## EXIT
exit

## ENJOY
