#!/bin/sh

### Package: pbp-install-mesa
### Version: v20200630.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## PBPTOOLSDIR
if [ -z $PBPTOOLSDIR ]; then
 PBPTOOLSDIR="`pwd`"
fi

## VARS
DATE=`date +%Y%m%d%H%M%S`
RESDIR=$PBPTOOLSDIR/resources
DEVDIR=$PBPTOOLSDIR/upstream
GITREPO=https://gitlab.freedesktop.org/mesa
GITTREE=mesa

## OVERRIDE master with GITBRANCH=(branch)
if [ -z $GITBRANCH ];then
 GITBRANCH=master
fi
echo "GITBRANCH selected is $GITBRANCH."

if [ -z $PATCHES ];then
 PATCHES=no
fi
echo "PATCHES selected is $PATCHES."

PKGDIR=$GITTREE\_$GITBRANCH

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS ]; then
 if [ $INSTALLDEPS = debian ]; then
  sudo apt-get -y build-dep mesa
  sudo apt-get -y install build-essential coreutils libc-bin git meson
 fi
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## PATCHES
if [ $PATCHES = yes ];then
 [ -f mesa_5584.patch ] || wget https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/5584.patch -O mesa_5584.patch
fi

## GIT
[ -d $PKGDIR ] || git clone --depth=1 $GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -f
git reset --hard HEAD
git pull

## CLEAN
rm -Rf pbp-build

## PATCHES
if [ $PATCHES = yes ];then
 patch -p1 < $DEVDIR/mesa_5584.patch
fi

## CONFIGURE
meson pbp-build --prefix=/usr/local --buildtype=release \
-Dplatforms=x11,wayland,drm,surfaceless -Ddri-drivers= \
-Dvulkan-drivers= -Dgallium-drivers=panfrost,kmsro,swrast \
-Dlibunwind=false -Dllvm=false

## BUILD
ninja -C pbp-build

## INSTALL
sudo ninja -C pbp-build install
sudo ldconfig

## EXIT
exit

## ENJOY
