#!/bin/sh

### Package: pbp-build-ffmpeg-v4l2request
### Version: v20200610.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: linux-hwaccel

## VARS
RESDIR=`pwd`/resources
DEVDIR=`pwd`/upstream
GITREPO=https://git.ffmpeg.org
GITTREE=ffmpeg
GITBRANCH=n4.2.3
PKGDIR=$GITTREE\_$GITBRANCH

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --depth=1 $GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -f
git reset --hard
git pull

## PATCH
patch -p1 < $RESDIR/ffmpeg/4.2.2/ffmpeg_v4l2-request-hwaccel-4.2.2-rkvdec_20200610.diff

## CONFIGURE
./configure --enable-v4l2-request --enable-libdrm --enable-libudev --enable-pic \
--enable-shared --prefix=/usr/local --incdir=/usr/local/include/aarch64-linux-gnu \
--libdir=/usr/local/lib/aarch64-linux-gnu --shlibdir=/usr/local/lib/aarch64-linux-gnu

## BUILD
make -j6

## INSTALL
sudo make install
sudo ldconfig

## EXIT
exit

## ENJOY
