#!/bin/sh

### Package: pbp-build-kodi
### Version: v20200613.1245
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: linux-hwaccel, ffmpeg-v4l2request

## VARS
DEVDIR=`pwd`/upstream
GITREPO=https://github.com/xbmc
GITTREE=xbmc
GITBRANCH=master
PKGDIR=$GITTREE\_$GITBRANCH

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --depth=1 $GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -f
git reset --hard
git pull

## CLEAN
rm -Rf pbp-build

## CONFIGURE
mkdir -p pbp-build
cd pbp-build
cmake .. \
-DCORE_PLATFORM_NAME=gbm \
-DGBM_RENDER_SYSTEM=gles \
-DFFMPEG_PATH=$SYSROOT_PREFIX/usr/local \
-DENABLE_TESTING=OFF

## MAKE
make -j `nproc`

## INSTALL
sudo make install
sudo ldconfig

## EXIT
exit

## ENJOY
