#!/bin/sh

### Package: pbp-update-systempartitions
### Version: v20200615.0830
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: linux
### USAGE: Pass $BLKDEV before command on terminal
### 		i.e. BLKDEV=/dev/nvme0n1 pbp-update-system-partitions

## VARS
DATE=`date +%Y%m%d%H%S`
RESDIR=`pwd`/resources
DEVDIR=`pwd`/upstream
GITBRANCH=v2.0
PKGDIR=pbp-update-systempartitions_$GITBRANCH

## DISPLAY BLKDEV
lsblk -a
echo "\n*** Select a device to write to with BLKDEV variable on commandline, i.e. /dev/mmcblk1 or /dev/nvme0n1."
echo "\n*** BLKDEV selected is $BLKDEV."
echo "\n*** Writing system partitions {idbloader,trust,uboot} to ${BLKDEV}p1 to p3.\n"

## CONFIRM BLKDEV
read -p "*** Continue to write to $BLKDEV ? Y/N:  " CONTINUE
case $CONTINUE in
 [Yy] ) echo "*** Continuing..." ;;
 [Nn] ) echo "*** Cancelling..." && exit ;;
 * ) echo "*** Y or N" && exit ;;
esac

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## WGET
mkdir -p $PKGDIR
cd $PKGDIR
[ -f idbloader.img ] || wget https://github.com/mrfixit2001/updates_repo/raw/$GITBRANCH/pinebook/filesystem/idbloader.img
[ -f trust.img ] || wget https://github.com/mrfixit2001/updates_repo/raw/$GITBRANCH/pinebook/filesystem/trust.img
[ -f uboot.img ] || wget https://github.com/mrfixit2001/updates_repo/raw/$GITBRANCH/pinebook/filesystem/uboot.img

## CHECK MD5
if md5sum -c $RESDIR/systempartitions/$GITBRANCH.md5 --quiet; then
 echo "\n*** MD5 checksum passed. Writing to device $BLKDEV. \n"
 sudo dd if=idbloader.img of=${BLKDEV}p1 bs=4096
 sudo dd if=uboot.img of=${BLKDEV}p2 bs=4096
 sudo dd if=trust.img of=${BLKDEV}p3 bs=4096
 echo "\n*** Wrote images to device $BLKDEV. Done. Exiting. \n"
else
 echo "MD5 failed. Did NOT write images to device $BLKDEV. Deleting IMG files and exiting. \n"
 rm idbloader.img trust.img uboot.img
fi

## EXIT
exit

## ENJOY
