#!/bin/sh

### Package: pbp-install-kodi
### Version: v20200630.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: linux, ffmpeg

## PBPTOOLSDIR
if [ -z $PBPTOOLSDIR ]; then
 PBPTOOLSDIR="`pwd`"
fi

## VARS
DATE=`date +%Y%m%d%H%M%S`
RESDIR=$PBPTOOLSDIR/resources
DEVDIR=$PBPTOOLSDIR/upstream
GITREPO=https://github.com/xbmc
GITTREE=xbmc
GITBRANCH=master
PKGDIR=$GITTREE\_$GITBRANCH

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS ]; then
 if [ $INSTALLDEPS = debian ]; then
  sudo apt-get -y build-dep kodi
  sudo apt-get -y install build-essential coreutils libc-bin git cmake make
 fi
fi

## OVERRIDES
# Override external with BUILDCONFIG=internal to bypass unavailable system dependencies.
if [ -z $BUILDCONFIG ]; then
 BUILDCONFIG=external
fi
echo "\n*** BUILDCONFIG selected is $BUILDCONFIG.\n"

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --depth=1 $GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -f
git reset --hard
git pull

## CLEAN
rm -Rf pbp-build

## CONFIGURE
mkdir -p pbp-build
cd pbp-build
if [ $BUILDCONFIG = external ]; then
 echo "\n*** Building with external BUILDCONFIG.\n"
 cmake .. \
 -DCMAKE_INSTALL_PREFIX=/usr/local \
 -DCMAKE_INSTALL_LIBDIR=/usr/local/lib/aarch64-linux-gnu \
 -DFFMPEG_PATH=/usr/local \
 -DCORE_PLATFORM_NAME=gbm \
 -DGBM_RENDER_SYSTEM=gles \
 -DENABLE_TESTING=OFF \
 -DENABLE_INTERNAL_CROSSGUID=OFF
fi
if [ $BUILDCONFIG = internal ]; then
 echo "\n*** Building with internal BUILDCONFIG.\n"
 cmake .. \
 -DCMAKE_INSTALL_PREFIX=/usr/local \
 -DCMAKE_INSTALL_LIBDIR=/usr/local/lib/aarch64-linux-gnu \
 -DFFMPEG_PATH=/usr/local \
 -DCORE_PLATFORM_NAME=gbm \
 -DGBM_RENDER_SYSTEM=gles \
 -DENABLE_TESTING=OFF \
 -DENABLE_INTERNAL_FMT=ON \
 -DENABLE_INTERNAL_CROSSGUID=ON \
 -DENABLE_INTERNAL_FSTRCMP=ON \
 -DENABLE_INTERNAL_FLATBUFFERS=ON \
 -DENABLE_INTERNAL_SPDLOG=ON
fi

## MAKE
make -j `nproc`

## INSTALL
sudo make install
sudo ldconfig

## EXIT
exit

## ENJOY
