#!/bin/sh

### Package: pbp-install-mesa
### Version: v20200619.1820
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## VARS
DEVDIR=`pwd`/upstream
GITREPO=https://gitlab.freedesktop.org/mesa
GITTREE=mesa

## OVERRIDE master with GITBRANCH=(branch)
if [ -z $GITBRANCH ];then
 GITBRANCH=master
fi
echo "GITBRANCH selected is $GITBRANCH."

PKGDIR=$GITTREE\_$GITBRANCH

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS ]; then
 if [ $INSTALLDEPS = debian ]; then
  sudo apt-get -y install build-essential coreutils libc-bin git meson
 fi
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --depth=1 $GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -f
git reset --hard
git pull

## CLEAN
rm -Rf pbp-build

## CONFIGURE
meson pbp-build --prefix=/usr/local --buildtype=release \
-Dplatforms=x11,wayland,drm,surfaceless -Ddri-drivers= \
-Dvulkan-drivers= -Dgallium-drivers=panfrost,kmsro,swrast \
-Dlibunwind=false -Dllvm=false

## BUILD
ninja -C pbp-build

## INSTALL
sudo ninja -C pbp-build install
sudo ldconfig

## EXIT
exit

# ENJOY
