#!/bin/sh

### Package: pbp-build-libudfread
### Version: v20200615.2009
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## VARS
DEVDIR=`pwd`/upstream
GITREPO=https://code.videolan.org/videolan
GITTREE=libudfread
GITBRANCH=master
PKGDIR=$GITTREE\_$GITBRANCH

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --depth=1 $GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -f
git reset --hard
git pull

## CONFIGURE
./bootstrap
./configure --prefix=/usr/local --libdir=/usr/local/lib/aarch64-linux-gnu

## MAKE
make -j `nproc`

## INSTALL
sudo make install
sudo ldconfig

## EXIT
exit

## ENJOY
