#!/bin/sh

### Package: pbp-build-linux-hwaccel
### Version: v20200613.2318
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## VARS
RESDIR=`pwd`/resources
DEVDIR=`pwd`/upstream
LINUXREL=5.7
#GITREPO=https://gitlab.manjaro.org/tsys
#GITTREE=linux-pinebook-pro
#GITBRANCH=v5.7
#PKGDIR=$GITTREE\_$GITBRANCH

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
#[ -d $PKGDIR ] || git clone --depth=1 $GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
#cd $PKGDIR
#git clean -f
#git reset --hard
#git pull

## LINUX
rm -Rf linux-$LINUXREL
[ -f linux-$LINUXREL.tar.xz ] || wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-$LINUXREL.tar.xz
tar xf linux-$LINUXREL.tar.xz
cd linux-$LINUXREL

## PATCH
patch -p1 < $RESDIR/linux/linux-pinebook-pro_v${LINUXREL}_current.diff
patch -p1 < $RESDIR/linux/linux-pinebook-pro_v${LINUXREL}_current-hwaccel.diff

## CONFIG
cp $RESDIR/linux/config_current .config

## OLDCONFIG
make oldconfig

## MENUCONFIG
make menuconfig

## MAKE
make -j `nproc` INITRD=yes KBUILD_IMAGE=arch/arm64/boot/Image bindeb-pkg

## EXIT
exit

## ENJOY

## POST SCRIPT
# install manually with dpkg
